spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/School
    username: SchoolAdmin
    password: 150304
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
