server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/School
    username: SchoolAdmin
    password: 150304
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    mvc:
      pathmatch:
       matching-strategy: ant_path_matcher